M48
; DRILL file {KiCad (6.0.5-0)} date Monday, 05 December 2022 at 01:18:36
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-05T01:18:36+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X2.975Y-4.375
X2.975Y-4.475
T2
X2.67Y-4.108
X3.458Y-5.032
T0
M30
